### ISSUE TITLE
Headless support

### ISSUE THREAD

**Issue by polyfloyd** [polyfloyd/shady#1]
Shady currently requires a `DISPLAY` to be set. That's not really needed.

Having headless support would make it easier to run it on servers that don't have Xorg installed and running.

**Comment by polyfloyd** [comment]
https://www.khronos.org/egl
https://devblogs.nvidia.com/egl-eye-opengl-visualization-without-x-server/

**Comment by SoupMeNot** [comment]
Feeling more like an enhancement than a real issue so I answer on this thread: Would it be possible to add an option for direct writing in the Raspberry framebuffer? Using pipes I was only able to display single images via the rgba32 output, but no animations. The X11 options always intereferes with the headless setup I want to achieve.

**Comment by polyfloyd** [comment]
Hey @SoupMeNot,

I am not familiar with the RPi Framebuffer, but there is an interface in the `encode` package that that is used by the majority of the `-ofmt` formats. You could write an implementation for this interface that writes to the framebuffer.
