### ISSUE TITLE
Rendering to video files is very slow (buffering problem?), see explanation

### ISSUE THREAD

**Issue by Tremeschin** [polyfloyd/shady#10]
_This is sorta a long write but I had to explain my findings and a bit of a context_

I'm a bit inexperienced with Golang but I dug on the code for a bit lurking for some slow // inefficient code or loops that were degrading performance a low then executing shady then piping its image contents from `-ofmt rgb24` to the stdout and piping to FFmpeg / FFprobe.

At first glance I thought this was very strange because on a Python project of mine I draw stuff to a OpenGL surface then get those images from the GPU, pipe to FFmpeg that is being ran with `ffmpeg = subprocess.Popen(command, stdout = subprocess.PIPE)` when write stuff with `ffmpeg.stdin.write(raw_image_data)`, this is basically if I sent to the stdout my raw arrays then piping to FFmpeg like `python script.py | ffmpeg -f rawvideo -i - ...`. I get about 30 frames per second with 1080p images being piped.

On your Golang code I eventually found the RGB24Format Encode function and saw those two for loops, thought that those were the main issue with such slow speeds (only about 10 fps at 1080p), tried searching somewhere for getting the full array in a single variable then returning it, I got it to work but speeds were still slow.

That was when I remembered about buffering, saw your function `openWriter` on the file `cmd/shady/main.go` and it looks like it is an unbuffered writing operation, that means the Go presumably would have to wait until the operation was executed step by step, much like how HDD buffering works, you kinda get a "Promise" of writing from the hard disk, it doesn't happen instantaneously as opposed to (most) programming languages default stdout implementations (for avoiding racing conditions I assume) so stuff are written linearly.

I tried changing the `io.Writer` to some quick searches to something like `bufio.NewWriterSize(os.Stdout, 1024*1024*16)` in hope I'd get a 16 MB buffer so we let Go write the frames as fast as it can to the OS's shell buffer.

Unfortunately that doesn't look like the case and I made very few progress after that.

I have some vague ideas on where this can be happening, one of those are simply that getting images out of the GPU is VERY expensive, but I'm a bit skeptical about this since my code can do almost 1080p30 (I'm very much limited by Python's slow nature at this point) and that if on `mpv` video player I run `mpv input.mkv --glsl-shader=./some.glsl -vg=gpu=w=1920:h=1080 -o video_with_shaders.mkv` (will only work on Linux OS) it literally saturates my CPU (mostly because lots of information and the encoder asking compute power) and renders about realtime to an output file.

Can you check based on these ideas if by any means we're being limited by OpenGL itself or Golang when writing the images to stdout?

It could be as explained previously some buffering problem as I don't think Golang would be slow enough to not be able to milk lots of raw image data for FFmpeg to render.

**Comment by polyfloyd** [comment]
The `rgb24` format already implements buffering in its implementation in `encode/encode.go`. My main suspect would be the rendering pipeline since I was somewhat inexperienced when I wrote it :sweat_smile: Another cause could be state updates that occur for every frame in the ShaderToy implementation.

However, one bit that can be optimized is the `flip` utility in `renderer/renderer.go` by moving it into the wrapping shader at the top of the file.

I currently can not spare any time to work on this myself, however I can give you a few pointers if you would like to investigate this further yourself :)

**Comment by Tremeschin** [comment]
> Another cause could be state updates that occur for every frame in the ShaderToy implementation.

Hmm could be, not really sure, I think at most we could be limited by GL's canvas flip limiting mechanism to vsync? That is if we don't use the double buffer thingy, I'm a bit inexperienced here also.

> However, one bit that can be optimized is the flip utility in renderer/renderer.go by moving it into the wrapping shader at the top of the file.

We can just apply an FFmpeg filter that flips the image!! (if it's what I'm thinking that is, upside down and mirrored vertically images because the order we read the pixels)

> I currently can not spare any time to work on this myself, however I can give you a few pointers if you would like to investigate this further yourself :)

Ah it's fine, take your time, I don't know if I'll really investigate further but writing down ideas here won't hurt for the future, right?

But yea, feel free to give some more ideas I can look in the code, don't promise solving it though :p

**Comment by Tremeschin** [comment]
Dude!! I changed `case stream <- &flip{Image: img}:` on `renderer/rendered.go` line 315 to `case stream <- img:` then applied that `-vf vflip` to the FFmpeg command and I render at 42 fps now and output video is totally fine!!

**Comment by Tremeschin** [comment]
Reporting back, [here's my commit](https://github.com/Tremeschin/shady/commit/cfa4bd9620c12801cc01590eaadec795dbb7e739) with some extra explanation, not production ready I think as we probably need to remove some code we won't be using anymore, but it's a start I guess

**Comment by polyfloyd** [comment]
Heyo @Tremeschin, I have pushed a commit that moves image flipping to OpenGL which should be a bit faster:

```
# Old
shady -i shaders/fiery-spiral.glsl -ofmt rgb24 -g 1920x1080 -f 60 | pv > /dev/null 
1.26GiB 0:00:20 [65.1MiB/s]

# New
shady -i shaders/fiery-spiral.glsl -ofmt rgb24 -g 1920x1080 -f 60 | pv > /dev/null 
1.43GiB 0:00:20 [73.8MiB/s]
```

So about 13% faster :)

Will close this issue now. Thanks for the help!

**Comment by Tremeschin** [comment]
But hey my sweetheart @polyfloyd , the actual most speed gain I got was by changing from `rgb24` to `rgba32` because letting FFmpeg scrap the alpha channel and let your Golang code output the whole frame at once (RGBA values) was A LOT faster!! 

Lemme demonstrate:

```
./shady -i shaders/example.glsl -ofmt rgb24 -g 1920x1080 -f 60 -d 20 | pv > /dev/null
6,95GiB 0:01:47 [66,4MiB/s]
```
This takes 1m47s for outputting 20 seconds of 1080p60, _however.._

```
./shady -i shaders/example.glsl -ofmt rgba32 -g 1920x1080 -f 60 -d 20 | pv > /dev/null
9,27GiB 0:00:06 [1,38GiB/s]
```

This took 6 seconds for outputting the same 20 seconds at 1080p60 and we went from 66.4 MiB/s to 1.38 GiB/s :p

**Comment by polyfloyd** [comment]
Huh you're right! I missed that detail :P

But I suppose that makes sense. The actual implementation of `image.Image` is `image.RGBA` so the `(RGBA32Format).Encode` can take its specialized branch and write the image buffer directly to the writer with one call.

I have done some quick tweaking of the RGB24 encoder and got it up to `6.09GiB 0:00:10 [ 612MiB/s]`. That's a big improvement, but still way short of what we are getting out of the RGBA32 format. Perhaps We could have OpenGL format the data to RGB24 for us so we could apply the same trick...

**Comment by Tremeschin** [comment]
> Perhaps We could have OpenGL format the data to RGB24 for us so we could apply the same trick...

Maybe expect a `vec3 mainImage()` output then just keep stuff how it is and we return `vec3(old_vec4_pixel);` ?

This is kinda hacky and I'm not sure how that will behave with jpeg / png compatibility, probably isn't a goooood idea to just change this and I'm not sure how hard it is for you to implement a quick something like `--gl-output-rgb24` and just swap this hacky workaround if user sends this flag..

**Comment by polyfloyd** [comment]
The rendering pipeline outputs as a stream of `image.Image`'s, so we can just have it return anything as long as it satisfies this interface. We also do not need to add new flags, we can just look at `-ofmt` and configure the renderer from that.

Will look into that later though, it's midnight where I live right now and I need to be up at a decent time tomorrow :P

**Comment by Tremeschin** [comment]
Ah, true we can just use the ofmt. Sure, take your time!!

**Comment by polyfloyd** [comment]
I have done some experimenting with using the RGB within OpenGL itself, but this does not seem to yield any performance improvements. I am going to leave this be for now.
