### ISSUE TITLE
Shadertoy buffer support?

### ISSUE THREAD

**Issue by jveres** [polyfloyd/shady#7]
Hi! Any plan to add Shadertoy BufferA-D support?

**Comment by polyfloyd** [comment]
Hey,

I have not used this functionality yet, so I have no plans myself. According to [this page](https://shadertoyunofficial.wordpress.com/2016/07/20/special-shadertoy-features/), it is sort of like exposing another shader as an image shader. Is that correct? What use case would it support that is currently not possible or practical?

**Comment by jveres** [comment]
I'm new to this but yes, that's correct.
Buffers are image shaders which can be used as a channel source.

Simple usage example: https://www.shadertoy.com/view/4l33zN
More complex example: https://www.shadertoy.com/view/ldtcWS

**Comment by jveres** [comment]
So I think it'd be a great addition.
Closing this ticket for now.
