### ISSUE TITLE
Unable to install shady

### ISSUE THREAD

**Issue by anziclone** [polyfloyd/shady#8]
Really appreciate your work with Shady and making it run on the led-cube. I'm trying to install shady on my mac and when I try to install shady, it gives me the following error:

**Command:** go get -u -v github.com/polyfloyd/shady/cmd/shady

github.com/polyfloyd/shady (download)
github.com/fsnotify/fsnotify (download)
get "golang.org/x/sys/unix": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
golang.org/x/sys (download)
get "golang.org/x/sys/internal/unsafeheader": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys/internal/unsafeheader?go-get=1
get "golang.org/x/sys/internal/unsafeheader": verifying non-authoritative meta tag
github.com/go-gl/gl (download)
github.com/go-gl/glfw (download)
github.com/mjibson/go-dsp (download)
github.com/tarm/serial (download)
github.com/polyfloyd/shady/egl
# pkg-config --cflags  -- egl
pkg-config: exec: "pkg-config": executable file not found in $PATH

**Comment by polyfloyd** [comment]
Looks like you need `pkg-config`. I'm not super familiar with Mac, but it might be in a package from Homebrew.
