### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by feiticeir0** [polyfloyd/shady#9]
Hi ! 
I'm trying to test your shady but I'm getting errors when compiling:

`
pi@raspberrypi:~ $ go get -u github.com/polyfloyd/shady/cmd/shady
# github.com/polyfloyd/shady/renderer
go/src/github.com/polyfloyd/shady/renderer/renderer.go:296:40: undefined: errors.Is
go/src/github.com/polyfloyd/shady/renderer/renderer.go:451:41: undefined: errors.Is
`

I've installed all the dependencies it said it needed, but I can't go further ... 
Using latest rasbian buster (debian_version 10.4)

I really wanted to try those shaders . Thank you for the instructions and all the work !

**Comment by polyfloyd** [comment]
What Go version do you have installed?

`errors.Is` is a function that was introduced in Go 1.13 which is somewhat recent.

Please install the latest version of Go

**Comment by feiticeir0** [comment]
Hi ! Thank you for the reply. I'm using the latest Go version available for the Raspberry PI
`
 go version
go version go1.11.6 linux/arm
`
But I've removed it and installed version 1.14.4 directly from google and it worked. Thank you. 
Will now try to see if I can run the shaders !

**Comment by feiticeir0** [comment]
I've tested it and it runs well. Just one question (probably a dumb one): How can I display it in the LED Cubes ? Is it possible like you've shown it in your page ? 

Thank you

**Comment by polyfloyd** [comment]
Yes, I'm using Shady for my LED-Cube. Shady can not output to the LED-panels by itself, you need Hzeller's RPi LED-panel library. This library has an example named `ledcat` which I added and works with Shady.

**Comment by feiticeir0** [comment]
Thank you !I've seen your instructions in the README. I already have the LED Panels software and done some examples and animations, but I would love to also see the shaders. When I've tried shaddy, but only two panels would light some pixels. I have some flicker and only a ugly rectangle on both... seen the problems section, will try and sort it out. any hints for 6 panels with the electrodragon panel driver... (the power is accounted for ! :) )

**Comment by polyfloyd** [comment]
I am not super familiar with driver boards, but it is mostly a matter of finding the right settings. You could also consider first getting an image to all the panels, then move on to displaying stuff with Shady and then getting the mapping right.
